### ISSUE TITLE
Select doesn't work on tables with "ON CONFLICT REPLACE"

### ISSUE THREAD

**Issue by Foxtrot** [alicebob/sqlittle#23]
Using Select() on a sqlite3 database table with a "ON CONFLICT REPLACE" constraint results in the following error:

`syntax error: unexpected ON, expecting ',' or ')'`

Code to reproduce:

```
        db, err := sqlittle.Open("test_broken.db")
	if err != nil {
		panic(err)
	}
	defer db.Close()

	err = db.Select("table1", func(r sqlittle.Row) {
		var (
			data int
		)
		_ = r.Scan(&data)
		fmt.Printf("%d\n", data)
	}, "data")

	if err != nil {
		panic(err)
	}
```

The schema is as follows:

`
CREATE TABLE table1 ( data INT, (UNIQUE data) ON CONFLICT REPLACE );
`

**Comment by alicebob** [comment]
There is a parser for the create statement, which doesn't know about that statement. Should not be too hard to add, in case you want to give it a try. Otherwise I'll do it in a bit.

**Comment by alicebob** [comment]
Version `v1.3.0` has your fix.
