### ISSUE TITLE
strange issue

### ISSUE THREAD

**Issue by vtolstov** [alicebob/sqlittle#34]
```
package main

import (
        "fmt"

        parser "github.com/alicebob/sqlittle/sql"
)

func main() {
        stmt, err := parser.Parse("SELECT * FROM foo")
        if err != nil {
              panic(err)
        }
        fmt.Printf("%#+v\n", stmt)
}
```

```
panic: syntax error

goroutine 1 [running]:
main.main()
        /home/vtolstov/p/main.go:12 +0xd0
exit status 2
```

**Comment by vtolstov** [comment]
why it fails? this is really the same as in testing cases.

**Comment by vtolstov** [comment]
mostly only asteriks is differs. Does it possible to not fail in this case? I want to reuse sql parser to parse sql in escaped url =)

**Comment by alicebob** [comment]
The SQL parser has support for `CREATE TABLE` statements, and basically no `SELECT`. The branch `driver` does fix the `SELECT * FROM`, but it still doesn't support much more than that. So if you need a fullblown SQL parser you either have to extend this code yourself, or find another lib :/

**Comment by sbinet** [comment]
FYI, I have used https://godoc.org/github.com/xwb1989/sqlparser to parse+handle SQL queries in other projects.
hth.

**Comment by vtolstov** [comment]
@sbinet Thanks, but as i see it havemany deps, I'm simply need tokenizer..

**Comment by vtolstov** [comment]
@alicebob Thank you, for now i need select *or some fields with simple conditions like != == <= >= And/Or ...

**Comment by alicebob** [comment]
Hi,

the version in `master` now solves the `*` problem, but it does not support `WHERE`. But if you have a look at `parser.go.y` you might be able to figure out how to do that yourself. There is already support for `WHERE` in `CREATE` statements in there, so it's really not much work to add that to `SELECT`.

**Comment by vtolstov** [comment]
ok, thanks!

**Comment by vtolstov** [comment]
does it possible to extract parser to dedicated package inside sqlittle ?
