### ISSUE TITLE
Latest GoDocs Don't Align with Latest Go Package Download

### ISSUE THREAD

**Issue by wicklander-bryant** [alicebob/sqlittle#36]
After downloading `sqlittle` using `go get github.com/alicebob/sqlittle` and attempting to get it working within my project, I noticed that there was a disconnect between the [latest documents for sqlittle](https://godoc.org/github.com/alicebob/sqlittle) and the [sqlittel pkg](https://pkg.go.dev/github.com/alicebob/sqlittle?tab=doc) that is downloaded. For example the documents show the function `func (*DB) SelectDone` (which I need for my usecase), but when I attempt to use this function I get the following error message:

```
db.SelectDone undefined (type *sqlittle.DB has no field or method SelectDone)go
```

This only happens when using `go mod` (which my large project uses), becuase it is getting the `sqlittle` code from `$GOPATH/pkg/mod/github.com/alicebob/sqlittle@v1.4.0`. If I create a new project that does **NOT** use `go mod` I am able to use `db.SelectDone` without any error because the `sqlittle` code that is used is found in `$GOPATH/src/github.com/alicebob/sqlittle`. After comparing, it's clear that the `sqlittle` code in `$GOPATH/pkg` is not upto date with the code in `$GOPATH/src` and the documentation. Could you please update the packaging so I can get `db.SelectDone` working in my project? 😁

**Comment by alicebob** [comment]
Hi,

I noticed I never made a release of the latest version. I did just now, `v1.5.0`, so that should solve the problem you're having with `go mod`.

**Comment by wicklander-bryant** [comment]
Thanks, that got things working for me 👍
